### PR TITLE
Solr 7

### PR DESCRIPTION
**Pull request by agentrickard**
## JIRA Ticket(s)

https://palantir.atlassian.net/browse/OPENSOURCE-31

## Description

This branch attempts to get Solr 7.7.2 up and running.

## Testing instructions

1. Checkout this branch
1. Run `vagrant halt && vagrant destroy`
1. Run `vagrant box update`
1. Run `vagrant up`
1. Run `/opt/solr/bin/solr -v` and confirm it is `7.7.2`
1. `vagrant ssh` and run `phing install-all`
1. Run `phing solr-reindex-all` 
1. Go to http://d8.fs-demo.local/search-app and confirm 32 records.

---

[Pull Request Guidelines](https://github.com/palantirnet/development_documentation/blob/master/guidelines/pr_review.md)

### CODE REVIEW

**Comment by agentrickard** [comment]
Strange. I had fixed that first error in the last commit.

For that second error, try running `phing install-d7`, it may have been a server error on the Drupal composer side.

**Comment by agentrickard** [comment]
Sigh. When I disable the proxy. I get a CORS error, so CORS is not setup properly here.

**Comment by agentrickard** [comment]
@russom-woldezghi Can you give this another try and let me know what happens?

**Comment by russom-woldezghi** [comment]
@agentrickard I am not seeing the first error I posted. 

I still getting issue with git clone command in `phing init`, however. I noticed that by changing the git clone path to a web URL got me past the error of `search_api_federated_solr` not being available for drush to enable in the d7 installation process. 

I changed the following in `build.xml:268-276`

```
              <echo message="git clone --branch=8.x-3.x https://github.com/palantirnet/search_api_federated_solr.git" />
              <exec command="git clone --branch=8.x-3.x https://github.com/palantirnet/search_api_federated_solr.git" dir="src" checkreturn="true" />
              <exec command="git remote add drupal https://git.drupalcode.org/project/search_api_federated_solr.git" dir="src/search_api_federated_solr" checkreturn="true" />
              <echo message="git clone --branch=8.x-3.x https://github.com/palantirnet/search_api_field_map.git" />
              <exec command="git clone --branch=8.x-3.x https://github.com/palantirnet/search_api_field_map.git" dir="src" checkreturn="true" />
              <exec command="git remote add drupal https://github.com/palantirnet/search_api_field_map.git" dir="src/search_api_field_map" checkreturn="true" />
              <echo message="git clone --branch=7.x-2.x https://github.com/palantirnet/search_api_federated_solr.git search_api_federated_solr-7.x" />
              <exec command="git clone --branch=7.x-2.x https://github.com/palantirnet/search_api_federated_solr.git search_api_federated_solr-7.x" dir="src" checkreturn="true" />
              <exec command="git remote add drupal https://github.com/palantirnet/search_api_federated_solr.git" dir="src/search_api_federated_solr-7.x" checkreturn="true" />
```

After making that change it was able to start the d7 installation but I ran into another error regarding where phing wasn't able to find the d7-domain `settings.php` file. Doesn't seem like the `settings.php` is being copied over for the d7-domain installation in time?. 

Screen Shot 2020-02-18 at 12 06 52 PM

**Comment by agentrickard** [comment]
The git change makes sense and would also apply to the `solr-4` branch.

**Comment by agentrickard** [comment]
These last two commits should fix the reported build issues.

I'm going to try destroying and rebuilding the entire project. Wish me luck.

**Comment by agentrickard** [comment]
@russom-woldezghi  This is all testing cleanly for me on a fresh built.

- `vagrant destroy`
- `cd rm -rf src`
- `vagrant up`
- `vagrant ssh`
- `vagrant install-all`
- `vagrant behat`

Expected behavior

- Vagrant should build cleanly
- Drupal sites should build cleanly
- Behat tests should pass

I changes things so that if you want dual-remotes for GIt checkouts, use `phing init-git`, which uses the git:// protocol for checkouts.

**Comment by russom-woldezghi** [comment]
@agentrickard 

- I was getting the following phing error (for `install-drupal-by-path` target), see below. Phing was trying to change permissions on the `settings.php` owned by `root` in Vagrant. Commenting the phing call to chmod the `settings.php`file at line **117**: 

`<chmod file="${drush.root}/${drupal.site}/settings.php" mode="777" />` 

helped resolve the error and complete the install without any errors. I was able to confirm the D8 demo site (http://d8.fs-demo.local/search-app) had 32 records I could search from.  

```
[phingcall] FileSystem::chmod() FAILED. Cannot chmod /var/www/federated-search-demo.local/web/d8/docroot/sites/default/settings.php. Mode 777.
[phingcall] /var/www/federated-search-demo.local/build.xml:38:52: Execution of the target buildfile failed. Aborting.

BUILD FAILED
/var/www/federated-search-demo.local/build.xml:13:40: Execution of the target buildfile failed. Aborting.
```


- I wanted to flag this error in the Drupal Status report page, relating associate schema for configuration items. This could be handled in a seperate ticket since we have an environment that builds. 

Screen Shot 2020-02-20 at 5 09 54 PM
 
You can view/filter/inspect config items here: http://d8.fs-demo.local/admin/reports/config-inspector

**Comment by agentrickard** [comment]
The permissions change error is caused by the fact that I removed that file after the last review. It is not checked in and is auto-created by Drupal.

We can put in a check if it exists, and remove / replace if it does.

The config schema are part of https://palantir.atlassian.net/browse/FS-10 and have a few patches ready, documented in that ticket.

**Comment by agentrickard** [comment]
@russom-woldezghi Can you go ahead and commit the change you made so I can test it?

**Comment by russom-woldezghi** [comment]
@agentrickard Posted the change.

**Comment by agentrickard** [comment]
I think we can finally merge this.

**Pull request merged**
