### PR TITLE
Fs 66 update core

### PR DESCRIPTION
**Pull request by agentrickard**
## JIRA Ticket(s)

- See ticket https://palantir.atlassian.net/browse/FS-66

## Description

Update core and dependencies to 8.8.5.

## Testing instructions

1. Run 'composer install' from the d8 directory
1. Ensure the latest versions of modules are installed.

## Additional Notes:

For some reason, this keeps installing 8.8.2?

---

[Pull Request Guidelines](https://github.com/palantirnet/development_documentation/blob/master/guidelines/pr_review.md)

### CODE REVIEW

**Comment by byrond** [comment]
On the D8 sites, I saw these errors during `drush updb`:
```
 [error]  Search API Federated Solr requires this module and version. Currently using Search API Field Map version  (Currently using Unresolved dependency Search API Field Map (Version &gt;=8.x-3.x required)) 
 [error]  Federated Styles requires this module and version. Currently using Search API Field Map version  (Currently using Unresolved dependency Search API Field Map (Version &gt;=8.x-3.x required)) 
```
I haven't seen any other issues so far. Is this what you were experiencing, @agentrickard?

Edit: Ok, I think that's just because Search API Field Map is checked out in the `src` directory, and the update module can't determine its version. The same warnings exist on the `3.x` branch.

**Comment by byrond** [comment]
@agentrickard, this works fine for me and installs 8.8.5 as expected.

**Comment by agentrickard** [comment]
Right, that `updb` error is because the -dev versions have no tags. It can be ignored.

I should have been more clear. `phing install-d8` is still installing 8.8.2 for me, even with this patch.

**Review by byrond — APPROVED** [review]
@agentrickard this looks good to me and showed the correct version for me after both an upgrade and fresh install. If the config changes look ok, this is good to merge!

**Comment by agentrickard** [comment]
I still get 8.8.2 after running `phing install-all`

Screen Shot 2020-05-18 at 10 08 11 AM

**Comment by agentrickard** [comment]
I tried to run `vagrant provision` thinking it might fix things, and I get:

```
TASK [common : Common | Update apt cache] **************************************
fatal: [federated-search-demo]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:The repository 'http://ppa.launchpad.net/duplicity-team/ppa/ubuntu xenial Release' does not have a Release file., W:Data from such a repository can't be authenticated and is therefore potentially dangerous to use., W:See apt-secure(8) manpage for repository creation and user configuration details., E:Failed to fetch http://ppa.launchpad.net/duplicity-team/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  403  Forbidden [IP: 91.189.95.83 80], E:Some index files failed to download. They have been ignored, or old ones used instead."}
```

**Comment by agentrickard** [comment]
@acidaniel Do you have some time this week to test out this PR?

**Comment by agentrickard** [comment]
I upgraded the-vagrant, did a `vagrant destroy` and `vagrant up` and I _still_ get Drupal 8.8.2 installed.

**Comment by agentrickard** [comment]
This seems to have updated and worked around all issues.

- Install Drupal 8.9.0
- Install Drupal 7.71
- Fix new error thrown by Behat
- Update React native application

@byrond this could use a re-review. I had to destroy and re-install the entire project (vagrant destroy && rm -rf federated-search-demo && new git checkout) to make the changes stick due to permissions issues.

**Comment by agentrickard** [comment]
In testing this again yesterday. `vagrant up` wants to update Composer to v2, which I think we can't do right now.

So I added a commit to disable the composer self-update.

When testing yesterday, `composer update` would spin for 30+ minutes without doing anything, so I don't know what's going on there.

Also see https://www.drupal.org/project/search_api_federated_solr/issues/3161672 for semver issues regarding the 4.x requirement for Search API Solr.

**Comment by Kbentham** [comment]
This is looking good to me, I updated the D7 version of core to 7.77.

**Review by agentrickard — COMMENTED** [review]
We should be installing Search API Solr 4.x and Drupal core 8.9.11 (my test installed 8.9.0).

**Pull request merged**
